### ISSUE TITLE
Improve load speeds by implementing lazy loading (aka virtual repeat)

### ISSUE THREAD

**Issue by snahrvar** [snahrvar/eatibl-app#22]
Priority: 6/10
Platform: Mobile
Description: Given the ever-growing list of restaurants on our platform, there is more and more content to load up front, since we load everything at once. This enhancement is to ensure we only load data 20 restaurants at one time (sorted by proximity).

**Comment by mattweason** [comment]
Did not do this. Ended up doing batch api requests.
