### ISSUE TITLE
One login for multiple accounts

### ISSUE THREAD

**Issue by GilbertEatibl** [snahrvar/eatibl-app#23]
Priority - 8
Platform - Restaurant login

Description - Some restaurant owners have multiple locations and need to access all Eatibl accounts with just one login. Perhaps a drop down menu to switch and choose a specific location. 

Thanks,
Gilbert

**Comment by snahrvar** [comment]
Yea this is a great point. My guess is we can have this ready by next week, but not likely this week.

**Comment by GilbertEatibl** [comment]
Okay that sounds good. Right now, I am manually adjusting the details for other accounts and not giving the client access to the other locations. 
This will def be more important in the near future when we start signing up corporate deals. Thanks!
