### ISSUE TITLE
B.GOOD - Multi account not working

### ISSUE THREAD

**Issue by GilbertEatibl** [snahrvar/eatibl-app#56]
Priority - 7

Description: Logged on thru web app and saw this:

![image](https://user-images.githubusercontent.com/39564572/40900253-b800a24c-6798-11e8-80c7-06fc0d869e24.png)

1. need to fix duplicate locations for Queen St W. 
2. need to add other locations (5 in total)

Many thanks,

Gilbert

**Comment by snahrvar** [comment]
This account now has 5 accounts associated with it, and the duplicate shouldn't show up anymore.
