### ISSUE TITLE
When date is set to today, have map mode say "No deal for today"

### ISSUE THREAD

**Issue by snahrvar** [snahrvar/eatibl-app#75]
Rather than no deal for June 19th (for example)

**Comment by GilbertEatibl** [comment]
"No deal for today" still sends a message that we didnt have any deals for that day. The user needs to know that there are deals all the time, and that they just might have missed out on the deals (i.e., if the user clicks on map marker at 7pm and the deals were on from 4-6pm, then they need to know that there was a chance, but the deals are done)

So I would suggest something along the lines of ... "Today's deals are sold out"

**Comment by snahrvar** [comment]
Ok, we'll keep this issue open and refine our messaging around that. You're right, we need a more encouraging message that reflects the deal opportunities.
