### ISSUE TITLE
'Import from Google' not working - Backend site

### ISSUE THREAD

**Issue by GilbertEatibl** [snahrvar/eatibl-app#77]
Priority = medium

when adding a resto to the backend, the "import" button from Google stays grayed out and the drop down suggestion options do not appear (See example)
![image](https://user-images.githubusercontent.com/39564572/41702973-dc6d9b3e-74ff-11e8-9b14-0c87d81a60f2.png)

This means that new restos are not being added to the maps?

Best regards,

Gilbert

**Comment by snahrvar** [comment]
Hey Gibs, are you still having this issue? I just tested it out on my end and everything is running. It's possible that your internet connection was down (or the less likely case where google was having an error). Let me know if you're still dealing with this one.
